version: '3.4'

services:
  posts.api:
    image: ${DOCKER_REGISTRY-}postsapi
    container_name: postsapi
    build:
      context: .
      dockerfile: Posts.API/Dockerfile
    depends_on:
      - articlesdb
    ports:
      - "7115:80"
  parser:
    image: ${DOCKER_REGISTRY-}parser
    container_name: parser
    build:
      context: .
      dockerfile: TengriNewsParser/Dockerfile
    depends_on:
      - articlesdb
  articlesdb:
    image: totajekeshova/news_articles_db
    container_name: articlesdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=reallyStrongPwd123
      - MSSQL_PID=Developer
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sql_data:${HOME}/Desktop/postsdb/data
      - sql_data:${HOME}/Desktop/postsdb/log
      - sql_data:${HOME}/Desktop/postsdb/secrets

volumes:
  sql_data:

  



